email: "jack@techteapot.com"
name: "Jack Hughes"
bio: "An experienced software engineer with 20+ years experience writing products for Microsoft Windows based operating systems as well as 17+ years experience hosting websites on Linux and Windows including e-commerce and CMS systems."
avatar: "/images/uploads/2007/06/001-150x150.jpg"
