baseURL: "https://techteapot.com/"
languageCode: "en-gb"
title: "The Tech Teapot"
# Theme extensions must appear before the website theme
theme: ["hugo-notice", "mainroad"]
enableEmoji: true
taxonomies:
  category: categories
  tag: tags
  series: series
disqusShortname: "techteapot-com"
googleAnalytics: "UA-71383-41"
enableRobotsTXT: true
frontmatter:
  lastmod: ["lastmod", ":default"]
