baseURL: "http://techteapot.com/"
languageCode: "en-gb"
title: "The Tech Teapot"
theme: "mainroad"
enableEmoji: true
taxonomies:
  category: categories
  tag: tags
disqusShortname: "techteapot-com"
googleAnalytics: "UA-71383-41"
enableRobotsTXT: true
