baseURL: "http://techteapot.com/"
languageCode: "en-gb"
title: "The Tech Teapot"
#theme: "ananke"
#theme: "eclectic"
#theme: "introduction"
theme: "mainroad"
enableEmoji: true
taxonomies:
  category: categories
  tag: tags
  series: series
