baseURL: "http://techteapot.com/"
languageCode: "en-gb"
title: "The Tech Teapot"
theme: "mainroad"
enableEmoji: true
taxonomies:
  category: categories
  tag: tags
disqusShortname: "" # Enable Disqus comments by entering your Disqus shortname
googleAnalytics: "UA-71383-41" # Enable Google Analytics by entering your tracking id
enableRobotsTXT: true
