main:                                       #    - Name of the menu
  - identifier: home
    name: Home
    url: /
    weight: 1
  - identifier: blog
    name: Blog
    url: /posts/
    weight: 2
  - identifier: contact
    name: Contact
    url: /contact/
    weight: 3
  - identifier: about
    name: About
    url: /about/
    weight: 4
  - identifier: subscribe
    name: Subscribe
    url: /sign-up/
    weight: 5
