# Primary navigation menu
main:
  - identifier: home
    name: Home
    url: /
    weight: 1
  - identifier: posts
    name: Posts
    url: /posts/
    weight: 2
  - identifier: series
    name: Series
    url: /series/
    weight: 3
  - identifier: contact
    name: Contact
    url: /contact/
    weight: 4
  - identifier: about
    name: About
    url: /about/
    weight: 5
  - identifier: subscribe
    name: Subscribe
    url: /sign-up/
    weight: 6

# Secondary navigation menu
footer:
  - identifier: privacy
    name: Privacy Policy
    url: /privacy/
    weight: 1
  - identifier: terms
    name: Terms & Conditions
    url: /terms/
    weight: 2
