main:                                       #    - Name of the menu
  - identifier: home
    name: Home
    url: /
    weight: 1
  - identifier: contact
    name: Contact
    url: /contact/
    weight: 2
  - identifier: about
    name: About
    url: /about
    weight: 3
  - identifier: subscribe
    name: Subscribe
    url: /sign-up/
    weight: 4
