copyright: "Jack Hughes"

style:
  vars:
    highlightColor: "#e22d30" # Override highlight color
    # Override font-family sets. Secondary font-family set responsible for pre, code, kbd, and samp tags font
    # Take care of different quotes OR escaping symbols in these params if necessary
    fontFamilyPrimary: "'Open Sans', Helvetica, Arial, sans-serif"
    fontFamilySecondary: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

logo:
  image: "images/logo.png" # Logo image. Path relative to "static"
  title: "The Tech Teapot" # Logo title, otherwise will use site title
  subtitle: "Your daily IT cuppa"

sidebar:
  home: "right" # Configure layout for home page
  list: "left"  # Configure layout for list pages
  single: false # Configure layout for single pages
  # Enable widgets in given order
  widgets: ["authorbio", "authorstackoverflow", "recent", "categories", "links", "taglist"]

widgets:
  recent_num: 5 # Set the number of articles in the "Recent articles" widget
  tags_counter: false # Enable counter for each tag in "Tags" widget

authorbox: true # Show authorbox at bottom of pages

# Include custom CSS files
# fancybox is used by hte foldergallery shortcode
customCSS: ["css/image.css", "https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css"]

# Used by foldergallery shortcode
customJS: ["https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js", "https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"]

# Order of post meta information
post_meta: ["author", "date", "categories"]
dateformat: "2006-01-02"
