color: "#71B180"
copyright: "Copyright &copy; 2006-2020 Jack Hughes. All Rights Reserved."
footer:
  - title: About
    content: This site is the digital home of Jack Hughes. He is a professional software developer specialising in the .NET stack. He currently works for [OPENXTRA Ltd](https://www.openxtra.co.uk/)...
  - title: Recent Blog Posts
    recents: blog
    recentCount: 7
  - title: Contact Us
    contact: true
style: green
logo: /image/logo.png
logo_small: /image/logo.png
about_us: This site is the digital home of Jack Hughes. He is a professional software developer specialising in the .NET stack. He currently works for [OPENXTRA Ltd](https://www.openxtra.co.uk/)...
#recent_posts:
#  enable: true
# ananke specific property
featured_image: "/image/cropped-14889914_10154725381259540_7668554272423940695_o-3.jpg"
