color: "#71B180"
copyright: "Copyright © 2006-2020 Jack Hughes. All Rights Reserved."
about_us: This site is the digital home of Jack Hughes. He is a professional software developer specialising in the .NET stack. He currently works for [OPENXTRA Ltd](https://www.openxtra.co.uk/)...
style:
  vars:
    highlightColor: "#e22d30" # Override highlight color
    # Override font-family sets. Secondary font-family set responsible for pre, code, kbd, and samp tags font
    # Take care of different quotes OR escaping symbols in these params if necessary
    fontFamilyPrimary: "'Open Sans', Helvetica, Arial, sans-serif"
    fontFamilySecondary: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

logo:
  image: "images/logo.png" # Logo image. Path relative to "static"
  title: "The Tech Teapot" # Logo title, otherwise will use site title
  subtitle: "Your daily IT cuppa"

sidebar:
  home: "right" # Configure layout for home page
  list: "left"  # Configure layout for list pages
  single: false # Configure layout for single pages
  # Enable widgets in given order
  widgets: ["authorbio", "authorstackoverflow", "recent", "categories", "taglist"]

widgets:
  recent_num: 5 # Set the number of articles in the "Recent articles" widget
  tags_counter: false # Enable counter for each tag in "Tags" widget

authorbox: true # Show authorbox at bottom of pages if true
